export const SUPABASE_URL = 'https://evaflxplucbfidlxyoaq.supabase.co';
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2YWZseHBsdWNiZmlkbHh5b2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4ODc2OTcsImV4cCI6MjA1MTQ2MzY5N30.Y7FtDEl5a1iiKfCRXeE7vp1pBo_ZXod8wBEID-1H_FI';

